create table chats
(
    id       bigint generated by default as identity
        constraint chats_pkey
            primary key,
    name     varchar(255),
    event_id bigint
        constraint uk_sud26hf1dpraqcqgo9s5q4r0y
            unique
);

alter table chats
    owner to postgres;