create table chats
(
    id       bigint generated by default as identity
        constraint chats_pkey
            primary key,
    name     varchar(255) not null,
    event_id bigint
        constraint fkeop5bdbqhehvh7fjxfnhualil
            references events
);

alter table chats
    owner to postgres;