create table events
(
    id          bigint generated by default as identity
        constraint events_pkey
            primary key,
    description varchar(255),
    name        varchar(255),
    start_date  date,
    chat_id     bigint
        constraint uk_a7y6h6thlk3c05ecyx4lu2lwh
            unique
        constraint fkduo9l2a1iakamwxautsodeqxq
            references chats
);

alter table events
    owner to postgres;