create table messages
(
    id        bigint generated by default as identity
        constraint messages_pkey
            primary key,
    send_date date,
    text      varchar(255),
    chat_id   bigint
        constraint fk64w44ngcpqp99ptcb9werdfmb
            references chats,
    user_id   bigint
        constraint fkpsmh6clh3csorw43eaodlqvkn
            references users
);

alter table messages
    owner to postgres;