create table roles
(
    id       bigint generated by default as identity
        constraint roles_pkey
            primary key,
    name     varchar(255),
    event_id bigint
        constraint fkqsmu03bmbu838d4iidn7ijdgn
            references events,
    user_id  bigint
        constraint fk97mxvrajhkq19dmvboprimeg1
            references users
);

alter table roles
    owner to postgres;